CadastroDeAlunos/Models/Cidades.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroDeAlunos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidades
    {
        public int id { get; set; }
        public string NomeCidade { get; set; }
        public string Estado { get; set; }
        public string Cep { get; set; }
    }
}

CadastroDeAlunos/Controllers/AlunosController.cs
using System;
using System.Collections;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Text.RegularExpressions;
using System.Web.Helpers;
using System.Web.Mvc;
using CadastroDeAlunos.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using static System.Data.Entity.Core.Objects.EntityFunctions;

namespace CadastroDeAlunos.Controllers
{
    [Authorize]
    public class AlunosController : Controller
    {
        private BdAlunoEntities db = new BdAlunoEntities();

        // GET: Alunos
        public async Task<ActionResult> Index(string sortOrder, string currebtFilter, string searchString, int? page, string coluna)
        {
            Session.RemoveAll();
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CodigoParamentro = String.IsNullOrEmpty(sortOrder) ? "Codigo_desc" : "";
            ViewBag.NomeParamentro = String.IsNullOrEmpty(sortOrder) ? "Nome_desc" : "";
            ViewBag.CpfParamentro = String.IsNullOrEmpty(sortOrder) ? "Cpf_desc" : "";
            ViewBag.DataNascimentoParamentro = String.IsNullOrEmpty(sortOrder) ? "DataNasc_desc" : "";
            ViewBag.DataCadastroParamentro = String.IsNullOrEmpty(sortOrder) ? "DataCadas_desc" : "";
            ViewBag.CidadeParamentro = String.IsNullOrEmpty(sortOrder) ? "Cidade_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            ViewBag.CurrentSort = searchString;
            ViewBag.coluna = coluna;

            var alunoModel = db.Pessoas.Where(c => c.idTpoPessoa == 1);

            if (!String.IsNullOrEmpty(searchString))
            {
                if (coluna == "id")
                {
                    Regex regexObj = new Regex(@"[^\d]");
                    string numero = regexObj.Replace(searchString, "");
                    if (numero != "")
                    {
                        int cod = Convert.ToInt32(numero);
                        alunoModel = alunoModel.Where(c => c.id == cod);
                    }
                }
                else if (coluna == "Nome")
                {
                    alunoModel = alunoModel.Where(b => b.Nome.ToUpper().Contains(searchString.ToUpper()));
                }
                else if (coluna == "Cpf")
                {
                    alunoModel = alunoModel.Where(b => b.Cpf.ToUpper().Contains(searchString.ToUpper()));
                }
                else if (coluna == "DataNascimento")
                {
                    Regex regexData = new Regex(@"[a-zA-Z]+");
                    var numero = regexData.Replace(searchString, "");
                    DateTime data = Convert.ToDateTime(numero);
                    Match match = Regex.Match(data.ToString(CultureInfo.InvariantCulture), @"^([1-9]|([012][0-9])|(3[01]))\/([0]{0,1}[1-9]|1[012])\/\d\d\d\d [012]{0,1}[0-9]:[0-6][0-9]:[0-6][0-9]$");
                    if (match.Success)
                    {
                        alunoModel = alunoModel.Where(c => TruncateTime(c.DataNascimento) == TruncateTime(data));
                    }
                }
                else if (coluna == "DataCadastro")
                {
                    Regex regexData = new Regex(@"[a-zA-Z]+");
                    var numero = regexData.Replace(searchString, "");
                    DateTime data = Convert.ToDateTime(numero);
                    Match match = Regex.Match(data.ToString(CultureInfo.InvariantCulture), @"^([1-9]|([012][0-9])|(3[01]))\/([0]{0,1}[1-9]|1[012])\/\d\d\d\d [012]{0,1}[0-9]:[0-6][0-9]:[0-6][0-9]$");
                    if (match.Success)
                    {
                        alunoModel = alunoModel.Where(c => TruncateTime(c.DataCadastro) == TruncateTime(data));
                    }
                }
            }
            switch (sortOrder)
            {
                case "Codigo_desc":
                    alunoModel = alunoModel.OrderBy(b => b.id);
                    break;
                case "Nome_desc":
                    alunoModel = alunoModel.OrderBy(b => b.Nome);
                    break;
                case "Cpf_desc":
                    alunoModel = alunoModel.OrderBy(b => b.Cpf);
                    break;
                case "Cep_desc":
                    alunoModel = alunoModel.OrderByDescending(b => b.DataNascimento);
                    break;
                case "DataNasc_desc":
                    alunoModel = alunoModel.OrderByDescending(b => b.DataNascimento);
                    break;
                case "DataCadas_desc":
                    alunoModel = alunoModel.OrderByDescending(b => b.DataCadastro);
                    break;
                default:
                    alunoModel = alunoModel.OrderByDescending(b => b.id);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(alunoModel.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult AlunoCidade(string searchString, string coluna)
        {
            IQueryable<Cidades> cidade = db.Cidades;
            if (!string.IsNullOrEmpty(searchString))
            {
                if (coluna == "Codigo")
                {
                    Regex regexObj = new Regex(@"[^\d]");
                    string numero = regexObj.Replace(searchString, "");
                    if (numero != "")
                    {
                        int cod = Convert.ToInt32(numero);
                        cidade = cidade.Where(c => c.id == cod);
                    }
                }
                else if (coluna == "NomeCidade")
                {
                    cidade = cidade.Where(c => c.NomeCidade.Contains(searchString));
                }
                else if (coluna == "Estado")
                {
                    cidade = cidade.Where(c => c.Estado.Contains(searchString));
                }
                else if (coluna == "Cep")
                {
                    cidade = cidade.Where(c => c.Cep.Contains(searchString));
                }
            }
            return View(cidade);
        }

        public ActionResult ListaAlunoCidade(string cidade)
        {
            @ViewBag.NomeCidade = cidade;
            var alunoCidade = db.Pessoas.Where(p => p.Cidade == cidade);

            return View("_ListaAlunosCidade", alunoCidade);
        }

        // GET: Alunos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoas pessoas = await db.Pessoas.FindAsync(id);
            if (pessoas == null)
            {
                return HttpNotFound();
            }
            return View(pessoas);
        }

        public ActionResult CreatePai()
        {
            return PartialView();
        }

        // POST: Alunos/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreatePai([Bind(Include = "id,idPessoa,idTpoPessoa,idUsuarioUpdate,Nome,Rg,Cpf,DataNascimento,Matricula,Idade,Sexo,Profissao,DataCadastro,DataAlteração,Telefone,Celular1,Celular2,Logradouro,Numero,Bairro,Complemento,Cidade,Estado,Cep")] Pessoas pessoas)
        {
            if (ModelState.IsValid)
            {
                pessoas.idTpoPessoa = 2;
                pessoas.DataCadastro = DateTime.Now; ;
                db.Pessoas.Add(pessoas);
                await db.SaveChangesAsync();
                Session["Pai"] = pessoas.id;
                return Json(new { success = true });
            }

            return PartialView(pessoas);
        }

        public ActionResult CreateMae()
        {
            return PartialView();
        }

        // POST: Alunos/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateMae([Bind(Include = "id,idPessoa,idTpoPessoa,idUsuarioUpdate,Nome,Rg,Cpf,DataNascimento,Matricula,Idade,Sexo,Profissao,DataCadastro,DataAlteração,Telefone,Celular1,Celular2,Logradouro,Numero,Bairro,Complemento,Cidade,Estado,Cep")] Pessoas pessoas)
        {
            if (ModelState.IsValid)
            {
                pessoas.idTpoPessoa = 3;
                pessoas.DataCadastro = DateTime.Now;
                db.Pessoas.Add(pessoas);
                await db.SaveChangesAsync();
                Session["Mae"] = pessoas.id;
                return Json(new { success = true });
            }

            return PartialView(pessoas);
        }

        // GET: Alunos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Alunos/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,idPessoa,idTpoPessoa,idUsuarioUpdate,Nome,Rg,Cpf,DataNascimento,Matricula,Idade,Sexo,Profissao,DataCadastro,DataAlteração,Telefone,Celular1,Celular2,Logradouro,Numero,Bairro,Complemento,Cidade,Estado,Cep")] Pessoas pessoas)
        {
            if (ModelState.IsValid)
            {
                VeriicaCidade(pessoas.Cidade, pessoas.Estado, pessoas.Cep);
                pessoas.idTpoPessoa = 1;
                pessoas.idUsuarioUpdate = User.Identity.GetUserId();

CadastroDeAlunos/Controllers/RelatoriosController.cs
using System.Linq;
using System.Web.Mvc;
using CadastroDeAlunos.Models;

namespace CadastroDeAlunos.Controllers
{
    public class RelatoriosController : Controller
    {
        private BdAlunoEntities db = new BdAlunoEntities();
        // GET: Relatorios
        public ActionResult Alunos()
        {
            ViewBag.NomeRelatorio = "Relatorio de Alunos";
            var alunos = db.Pessoas.Where(a => a.idTpoPessoa == 1).OrderBy(a => a.Cidade);
            return View(alunos.ToList());
        }

        public ActionResult Cidades()
        {
            ViewBag.NomeRelatorio = "Relatorio de Cidades";
            var cidades = db.Cidades.OrderBy(c => c.NomeCidade);
            return View(cidades.ToList());
        }

        public ActionResult AlunosCidades()
        {
            ViewBag.NomeRelatorio = "Relatorio de Alunos por Cidade";
            ViewBag.Cidade = db.Cidades.Distinct().OrderBy(c => c.NomeCidade).Select(c => c.NomeCidade);
            
            return View();
        }

        public ActionResult ListaAlunosCidades(string nomeCidade)
        {
            var alunos = db.Pessoas.Where(p => p.idTpoPessoa == 1 && p.Cidade == nomeCidade).OrderBy(p => p.Nome);
            ViewBag.NomeCidade = nomeCidade;
            return View(alunos.ToList());
        }
    }
}

///*http://www.devmedia.com.br/como-gerar-relatorios-no-asp-net-mvc/33921*/

CadastroDeAlunos/Views/Relatorios/Alunos.cshtml
@model IEnumerable<CadastroDeAlunos.Models.Pessoas>
@{
    ViewBag.Title = "Alunos";
    Layout = "~/Views/Shared/_LayoutRelatorio.cshtml";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cpf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Celular1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Celular2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logradouro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bairro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Complemento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cep)
        </th>
    </tr>
@foreach (var item in Model) {
   
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rg)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cpf)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataNascimento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Idade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Celular1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Celular2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Logradouro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Numero)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bairro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Complemento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cep)
        </td>
    </tr>
}

</table>

CadastroDeAlunos/Views/Relatorios/AlunosCidades.cshtml
@{
    ViewBag.Title = "AlunosCidades";
    Layout = "~/Views/Shared/_LayoutRelatorio.cshtml";
}

@foreach (var item in ViewBag.Cidade) {
    
            @Html.Action("ListaAlunosCidades", "Relatorios", new { @nomeCidade = item })
        
}

CadastroDeAlunos/Views/Relatorios/Cidades.cshtml
@model IEnumerable<CadastroDeAlunos.Models.Cidades>

@{
    ViewBag.Title = "Cidades";
    Layout = "~/Views/Shared/_LayoutRelatorio.cshtml";
}

<h2>Cidades</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NomeCidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cep)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NomeCidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cep)
        </td>
    </tr>
}

</table>

CadastroDeAlunos/Views/Relatorios/Index.cshtml
@{
    ViewBag.Title = "Index";
}

CadastroDeAlunos/Views/Relatorios/ListaAlunosCidades.cshtml
@model IEnumerable<CadastroDeAlunos.Models.Pessoas>

@{
    Layout = null;
}
<div><h3> Alunos de @ViewBag.NomeCidade</h3></div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cpf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Celular1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Celular2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logradouro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bairro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Complemento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cep)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataAlteração)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rg)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cpf)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataNascimento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Idade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Celular1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Celular2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Logradouro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Numero)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bairro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Complemento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cep)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataCadastro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataAlteração)
        </td>
    </tr>
}

</table>