CadastroDeAlunos/Controllers/AlunosController.cs
using System;
using System.Collections;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Text.RegularExpressions;
using System.Web.Helpers;
using System.Web.Mvc;
using CadastroDeAlunos.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using static System.Data.Entity.Core.Objects.EntityFunctions;

namespace CadastroDeAlunos.Controllers
{
    [Authorize]
    public class AlunosController : Controller
    {
        private BdAlunoEntities db = new BdAlunoEntities();

        // GET: Alunos
        public async Task<ActionResult> Index(string sortOrder, string currebtFilter, string searchString, int? page, string coluna)
        {
            Session.RemoveAll();
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CodigoParamentro = String.IsNullOrEmpty(sortOrder) ? "Codigo_desc" : "";
            ViewBag.NomeParamentro = String.IsNullOrEmpty(sortOrder) ? "Nome_desc" : "";
            ViewBag.CpfParamentro = String.IsNullOrEmpty(sortOrder) ? "Cpf_desc" : "";
            ViewBag.DataNascimentoParamentro = String.IsNullOrEmpty(sortOrder) ? "DataNasc_desc" : "";
            ViewBag.DataCadastroParamentro = String.IsNullOrEmpty(sortOrder) ? "DataCadas_desc" : "";
            ViewBag.CidadeParamentro = String.IsNullOrEmpty(sortOrder) ? "Cidade_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            ViewBag.CurrentSort = searchString;
            ViewBag.coluna = coluna;

            var alunoModel = db.Pessoas.Where(c => c.idTpoPessoa == 1);

            if (!String.IsNullOrEmpty(searchString))
            {
                if (coluna == "id")
                {
                    Regex regexObj = new Regex(@"[^\d]");
                    string numero = regexObj.Replace(searchString, "");
                    if (numero != "")
                    {
                        int cod = Convert.ToInt32(numero);
                        alunoModel = alunoModel.Where(c => c.id == cod);
                    }
                }
                else if (coluna == "Nome")
                {
                    alunoModel = alunoModel.Where(b => b.Nome.ToUpper().Contains(searchString.ToUpper()));
                }
                else if (coluna == "Cpf")
                {
                    alunoModel = alunoModel.Where(b => b.Cpf.ToUpper().Contains(searchString.ToUpper()));
                }
                else if (coluna == "DataNascimento")
                {
                    Regex regexData = new Regex(@"[a-zA-Z]+");
                    var numero = regexData.Replace(searchString, "");
                    DateTime data = Convert.ToDateTime(numero);
                    Match match = Regex.Match(data.ToString(CultureInfo.InvariantCulture), @"^([1-9]|([012][0-9])|(3[01]))\/([0]{0,1}[1-9]|1[012])\/\d\d\d\d [012]{0,1}[0-9]:[0-6][0-9]:[0-6][0-9]$");
                    if (match.Success)
                    {
                        alunoModel = alunoModel.Where(c => TruncateTime(c.DataNascimento) == TruncateTime(data));
                    }
                }
                else if (coluna == "DataCadastro")
                {
                    Regex regexData = new Regex(@"[a-zA-Z]+");
                    var numero = regexData.Replace(searchString, "");
                    DateTime data = Convert.ToDateTime(numero);
                    Match match = Regex.Match(data.ToString(CultureInfo.InvariantCulture), @"^([1-9]|([012][0-9])|(3[01]))\/([0]{0,1}[1-9]|1[012])\/\d\d\d\d [012]{0,1}[0-9]:[0-6][0-9]:[0-6][0-9]$");
                    if (match.Success)
                    {
                        alunoModel = alunoModel.Where(c => TruncateTime(c.DataCadastro) == TruncateTime(data));
                    }
                }
            }
            switch (sortOrder)
            {
                case "Codigo_desc":
                    alunoModel = alunoModel.OrderBy(b => b.id);
                    break;
                case "Nome_desc":
                    alunoModel = alunoModel.OrderBy(b => b.Nome);
                    break;
                case "Cpf_desc":
                    alunoModel = alunoModel.OrderBy(b => b.Cpf);
                    break;
                case "Cep_desc":
                    alunoModel = alunoModel.OrderByDescending(b => b.DataNascimento);
                    break;
                case "DataNasc_desc":
                    alunoModel = alunoModel.OrderByDescending(b => b.DataNascimento);
                    break;
                case "DataCadas_desc":
                    alunoModel = alunoModel.OrderByDescending(b => b.DataCadastro);
                    break;
                default:
                    alunoModel = alunoModel.OrderByDescending(b => b.id);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(alunoModel.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult AlunoCidade(string searchString, string coluna)
        {
            IQueryable<Cidades> cidade = db.Cidades;
            if (!string.IsNullOrEmpty(searchString))
            {
                if (coluna == "Codigo")
                {
                    Regex regexObj = new Regex(@"[^\d]");
                    string numero = regexObj.Replace(searchString, "");
                    if (numero != "")
                    {
                        int cod = Convert.ToInt32(numero);
                        cidade = cidade.Where(c => c.id == cod);
                    }
                }
                else if (coluna == "NomeCidade")
                {
                    cidade = cidade.Where(c => c.NomeCidade.Contains(searchString));
                }
                else if (coluna == "Estado")
                {
                    cidade = cidade.Where(c => c.Estado.Contains(searchString));
                }
                else if (coluna == "Cep")
                {
                    cidade = cidade.Where(c => c.Cep.Contains(searchString));
                }
            }
            return View(cidade);
        }

        public ActionResult ListaAlunoCidade(string cidade)
        {
            @ViewBag.NomeCidade = cidade;
            var alunoCidade = db.Pessoas.Where(p => p.Cidade == cidade);

            return View("_ListaAlunosCidade", alunoCidade);
        }

        // GET: Alunos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoas pessoas = await db.Pessoas.FindAsync(id);
            if (pessoas == null)
            {
                return HttpNotFound();
            }
            return View(pessoas);
        }

        public ActionResult CreatePai()
        {
            return PartialView();
        }

        // POST: Alunos/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreatePai([Bind(Include = "id,idPessoa,idTpoPessoa,idUsuarioUpdate,Nome,Rg,Cpf,DataNascimento,Matricula,Idade,Sexo,Profissao,DataCadastro,DataAlteração,Telefone,Celular1,Celular2,Logradouro,Numero,Bairro,Complemento,Cidade,Estado,Cep")] Pessoas pessoas)
        {
            if (ModelState.IsValid)
            {
                pessoas.idTpoPessoa = 2;
                pessoas.DataCadastro = DateTime.Now; ;
                db.Pessoas.Add(pessoas);
                await db.SaveChangesAsync();
                Session["Pai"] = pessoas.id;
                return Json(new { success = true });
            }

            return PartialView(pessoas);
        }

        public ActionResult CreateMae()
        {
            return PartialView();
        }

        // POST: Alunos/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateMae([Bind(Include = "id,idPessoa,idTpoPessoa,idUsuarioUpdate,Nome,Rg,Cpf,DataNascimento,Matricula,Idade,Sexo,Profissao,DataCadastro,DataAlteração,Telefone,Celular1,Celular2,Logradouro,Numero,Bairro,Complemento,Cidade,Estado,Cep")] Pessoas pessoas)
        {
            if (ModelState.IsValid)
            {
                pessoas.idTpoPessoa = 3;
                pessoas.DataCadastro = DateTime.Now;
                db.Pessoas.Add(pessoas);
                await db.SaveChangesAsync();
                Session["Mae"] = pessoas.id;
                return Json(new { success = true });
            }

            return PartialView(pessoas);
        }

        // GET: Alunos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Alunos/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,idPessoa,idTpoPessoa,idUsuarioUpdate,Nome,Rg,Cpf,DataNascimento,Matricula,Idade,Sexo,Profissao,DataCadastro,DataAlteração,Telefone,Celular1,Celular2,Logradouro,Numero,Bairro,Complemento,Cidade,Estado,Cep")] Pessoas pessoas)
        {
            if (ModelState.IsValid)
            {
                VeriicaCidade(pessoas.Cidade, pessoas.Estado, pessoas.Cep);
                pessoas.idTpoPessoa = 1;
                pessoas.idUsuarioUpdate = User.Identity.GetUserId();

CadastroDeAlunos/Controllers/CidadesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using CadastroDeAlunos.Models;
using PagedList;

namespace CadastroDeAlunos.Controllers
{
    [Authorize]
    public class CidadesController : Controller
    {
        private BdAlunoEntities db = new BdAlunoEntities();
        
        
        // GET: Aluno/Cidades
        public async Task<ActionResult> Index(string sortOrder, string currebtFilter, string searchString, int? page, string coluna)
        {
            Session.RemoveAll();
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CidadeParamentro = String.IsNullOrEmpty(sortOrder) ? "Cidade_desc" : "";
            ViewBag.EstadoParamentro = String.IsNullOrEmpty(sortOrder) ? "Estado_desc" : "";
            ViewBag.CepParamentro = String.IsNullOrEmpty(sortOrder) ? "Cep_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            ViewBag.CurrentSort = searchString;

            var cidadeModel = from c in db.Cidades select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                if (coluna == "id")
                {
                    cidadeModel = cidadeModel.Where(b => b.id == 6);
                }
                else if (coluna == "NomeCidade")
                {
                    cidadeModel = cidadeModel.Where(b => b.NomeCidade.ToUpper().Contains(searchString.ToUpper()));
                }
                else if (coluna == "Estado")
                {
                    cidadeModel = cidadeModel.Where(b => b.Estado.ToUpper().Contains(searchString.ToUpper()));
                }
                else if (coluna == "Cep")
                {
                    cidadeModel = cidadeModel.Where(b => b.Cep.ToUpper().Contains(searchString.ToUpper()));
                }
                else
                {
                    cidadeModel = cidadeModel.Where(b => b.NomeCidade.ToUpper().Contains(searchString.ToUpper()));
                }
                //modcasamento = modcasamento.Where(b => b.NOME_NOIVO.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Cidade_desc":
                    cidadeModel = cidadeModel.OrderBy(b => b.NomeCidade);
                    break;
                case "Estado_desc":
                    cidadeModel = cidadeModel.OrderBy(b => b.Estado);
                    break;
                case "Cep_desc":
                    cidadeModel = cidadeModel.OrderByDescending(b => b.Cep);
                    break;
                default:
                    cidadeModel = cidadeModel.OrderByDescending(b => b.id);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(cidadeModel.ToPagedList(pageNumber, pageSize));
        }

        // GET: Aluno/Cidades/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cidades cidades = await db.Cidades.FindAsync(id);
            if (cidades == null)
            {
                return HttpNotFound();
            }
            return View(cidades);
        }

        // GET: Aluno/Cidades/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Aluno/Cidades/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,NomeCidade,Estado,Cep")] Cidades cidades)
        {
            if (ModelState.IsValid)
            {
                db.Cidades.Add(cidades);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(cidades);
        }

        public PartialViewResult CreateCidade()
        {
            Cidades cidades = new Cidades();
            return PartialView("CidadePartial", cidades);
        }
        

        // GET: Aluno/Cidades/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cidades cidades = await db.Cidades.FindAsync(id);
            if (cidades == null)
            {
                return HttpNotFound();
            }
            return View(cidades);
        }

        // POST: Aluno/Cidades/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,NomeCidade,Estado,Cep")] Cidades cidades)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cidades).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(cidades);
        }

        // GET: Aluno/Cidades/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cidades cidades = await db.Cidades.FindAsync(id);
            if (cidades == null)
            {
                return HttpNotFound();
            }
            return View(cidades);
        }

        // POST: Aluno/Cidades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Cidades cidades = await db.Cidades.FindAsync(id);
            db.Cidades.Remove(cidades);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CadastroDeAlunos/Views/Shared/MenuPartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Cadastro de Alunos", "Index", "Alunos")</li>
                <li>@Html.ActionLink("Cadastro de Cidades", "Index", "Cidades")</li>
                <li>@Html.ActionLink("Alunos Por Cidade", "AlunoCidade", "Alunos")</li>
                <li>@Html.ActionLink("Relatorios", "Alunos", "Relatorios")</li>
                <li>@Html.ActionLink("Graficos", "Index", "Graficos")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    }
}
else
{
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Início", "Index", "Home")</li>
            <li>@Html.ActionLink("Sobre", "About", "Home")</li>
            <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
        </ul>
        @Html.Partial("_LoginPartial")
    </div>
}

CadastroDeAlunos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @Html.Partial("MenuPartial")
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        function InputToUpper(obj) {
            if (obj.value !== "") {
                obj.value = obj.value.toUpperCase();
            }
        }

        function InputUpper(obj) {
            if (obj.value !== "") {
                obj.value = obj.value.toLowerCase();
            }
        }

        function formatar(mascara, documento) {
            var i = documento.value.length;
            var saida = mascara.substring(0, 1);
            var texto = mascara.substring(i);

            if (texto.substring(0, 1) !== saida) {
                documento.value += texto.substring(0, 1);
            }
        }

    </script>

</body>
</html>

CadastroDeAlunos/Views/Shared/_LayoutRelatorio.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @{
                    string relatorio = ViewBag.NomeRelatorio;
                }
                @Html.ActionLink(relatorio, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>